### ISSUE TITLE
filter似乎没有生效

### ISSUE THREAD

**Issue by MacJayLee** [nonconvextech/ftlog#1]
我用的官方的例子
<img width="754" alt="WeChatcb3ad14698769dbc0f5b4b1fc93f9da0" src="https://user-images.githubusercontent.com/38428395/210722361-976910e9-b46f-43c6-aab6-1654c66649b4.png">
本意是current.log负责记录info的内容
ftlog-appender.log负责记录error的内容
分别用info！和error！打印
结果info和err全部都记录在current.log里面了
<img width="615" alt="WeChat54c36478b56e1a5f927e09b887ae639f" src="https://user-images.githubusercontent.com/38428395/210722667-3faa5ab1-a392-4d1c-b535-eda093a06d77.png">
而appender定义的ftlog-appender.log没有任何error的内容

是我理解错了吗？

**Comment by fMeow** [comment]
可能文档没写清楚，filter的本意是允许特定target使用独立的导出配置，然后这里target是module path。

您给的的例子中预期行为是：
在ftlog::appender这个路径下的日志，用“ftlog-appender”这个日志输出配置，并且会过滤掉只打印Error以上的日志。

全部都记录在current.log里面了是因为info!和error!调用的不在ftlog::appender路径下面，所以会走root配置。

**Comment by fMeow** [comment]
一般就是按照您文件所在项目路径，比如有个bin项目叫my-project:
main.rs
```rust
mod my_mod1 {
    // filters设置为"my_project::my_mod1"对本mod生效
   info!("打印到mod1.log");
}
mod my_mod2 {
    // filters设置为"my_project::my_mod2"对本mod生效
    info!("这条日志会被忽略");
    error!("打印到mod2.log");
}
fn main(){
    let writer = FileAppender::rotate_with_expire("./default.log", Period::Day, Duration::weeks(1));
    let logger = ftlog::Builder::new()
        .max_log_level(LevelFilter::Info)
        .root(writer)
        .filter("my_project::mod1", "mod1", LevelFilter::Info)
        .appender("mod1", FileAppender::new("mod1.log"))
        .filter("my_project::mod2", "mod1", LevelFilter::Error)
        .appender("mod2", FileAppender::new("mod2.log"))
        .build()
        .expect("logger build failed");
}

```
