### ISSUE TITLE
时间不对，怎么加+8呢

### ISSUE THREAD

**Issue by 107295472** [nonconvextech/ftlog#10]

**Comment by fMeow** [comment]
可以在构建logger的时候[指定固定时区](https://docs.rs/ftlog/0.2.10/ftlog/struct.Builder.html#method.fixed_timezone)
```rust
use time::UtcOffset;

let utc_p8_tz = UtcOffset::from_hms(8, 0, 0).unwrap();
ftlog::builder().fixed_timezone(utc_p8_tz).try_init().unwrap();
```

**Comment by 107295472** [comment]
谢谢

**Comment by 107295472** [comment]
> 可以在构建logger的时候[指定固定时区](https://docs.rs/ftlog/0.2.10/ftlog/struct.Builder.html#method.fixed_timezone)
> 
> ```rust
> use time::UtcOffset;
> 
> let utc_p8_tz = UtcOffset::from_hms(8, 0, 0).unwrap();
> ftlog::builder().fixed_timezone(utc_p8_tz).try_init().unwrap();
> ```

2023-10-25 03:50:11.927030 0ms ERROR main 没效果呢

**Comment by 107295472** [comment]
let utc_p8_tz = UtcOffset::from_hms(8, 0, 0).unwrap();
`ftlog::builder()
        // global max log level
        .max_log_level(LevelFilter::Info)
        // custom timestamp format
        .time_format(time_format)
        // set global log formatter
        .format(FtLogFormatter)
        .fixed_timezone(utc_p8_tz)
        // use bounded channel to avoid large memory comsumption when overwhelmed with logs
        // Set `false` to tell ftlog to discard excessive logs.
        // Set `true` to block log call to wait for log thread.
        // here is the default settings
        .bounded(100_000, false) // .unbounded()
        // define root appender, pass anything that is Write and Send
        // omit `Builder::root` will write to stderr
        .root(
            FileAppender::builder()
                .path(log_path)
                .rotate(Period::Day)
                .expire(Duration::days(7))
                .build(),
        )
        // Do not convert to local timezone for timestamp, this does not affect worker thread,
        // but can boost log thread performance (higher throughput).
        .utc()
        // level filter for root appender
        .root_log_level(LevelFilter::Error)
        // write logs in ftlog::appender to "./ftlog-appender.log" instead of "./current.log"
        // .filter("ftlog::appender", "ftlog-appender", LevelFilter::Error)
        // .appender("ftlog-appender", FileAppender::new("ftlog-appender.log"))
        .try_init()
        .expect("logger build or set failed");`

**Comment by fMeow** [comment]
```diff
 let utc_p8_tz = UtcOffset::from_hms(8, 0, 0).unwrap();
ftlog::builder()
        // global max log level
        .max_log_level(LevelFilter::Info)
        // custom timestamp format
        .time_format(time_format)
        // set global log formatter
        .format(FtLogFormatter)
        .fixed_timezone(utc_p8_tz)
        // use bounded channel to avoid large memory comsumption when overwhelmed with logs
        // Set `false` to tell ftlog to discard excessive logs.
        // Set `true` to block log call to wait for log thread.
        // here is the default settings
        .bounded(100_000, false) // .unbounded()
        // define root appender, pass anything that is Write and Send
        // omit `Builder::root` will write to stderr
        .root(
            FileAppender::builder()
                .path(log_path)
                .rotate(Period::Day)
                .expire(Duration::days(7))
                .build(),
        )
        // Do not convert to local timezone for timestamp, this does not affect worker thread,
        // but can boost log thread performance (higher throughput).
-       .utc() // <- 这里指定了格林尼治时区覆盖了前面了东八区的配置
        // level filter for root appender
        .root_log_level(LevelFilter::Error)
        // write logs in ftlog::appender to "./ftlog-appender.log" instead of "./current.log"
        // .filter("ftlog::appender", "ftlog-appender", LevelFilter::Error)
        // .appender("ftlog-appender", FileAppender::new("ftlog-appender.log"))
        .try_init()
        .expect("logger build or set failed");
```

**Comment by 107295472** [comment]
谢谢，utc去掉就好了
