### ISSUE TITLE
How do I separate different log levels into different files?

### ISSUE THREAD

**Issue by Remalloc** [nonconvextech/ftlog#12]
Hello everyone. I want to distinguish log levels by file, like info.log and error.log, but I don't know how to implement this.

Below code does not work:
```rust
let log_file = format!("{}/{}.log", log_dir, log_name);
let err_log_file = format!("{}/{}.err.log", log_dir, log_name);
let info_writer =
	FileAppender::rotate_with_expire(&log_file, Period::Day, Duration::days(3));
let error_writer =
	FileAppender::rotate_with_expire(&log_file, Period::Day, Duration::days(3));
ftlog::Builder::new()
	.root_log_level(LevelFilter::Info)
	.root(info_writer)
	.filter("", "error_appender", LevelFilter::Error)
	.appender("error_appender", error_writer)
	.try_init()
	.expect("logger build or set failed");
```

**Comment by fMeow** [comment]
I don't think it currently possible in ftlog to direct different level to individual files.

**Comment by Remalloc** [comment]
> I don't think it currently possible in ftlog to direct different level to individual files.

Do you know if any other loggers have this feature?

**Comment by fMeow** [comment]
idk. Maybe log4rs?

**Comment by Remalloc** [comment]
> log4rs

thx. I decided to switch to it because I truly need this feature.
