### ISSUE TITLE
既然开源了，就好好写注释吧

### ISSUE THREAD

**Issue by levihuayuzhang** [nonconvextech/ftlog#17]
既然开源了，就好好写注释吧，别怕被优化😆

**Comment by fMeow** [comment]
可以看[docs.rs](https://docs.rs/ftlog/latest/ftlog/)上的注释。

具体哪里不清楚可以明确说明下，我们会进行补充，也欢迎提交PR。

**Comment by levihuayuzhang** [comment]
好的，谢谢解惑
