### ISSUE TITLE
支持控制台输出么

### ISSUE THREAD

**Issue by Tomao2014** [nonconvextech/ftlog#19]
你好，请问开发环境，支持控制台输出么？ 视乎没找到相关的配置。

另外，进程结束时，如何Recv清空Channel的数据到文件。

**Comment by fMeow** [comment]
> 支持控制台输出么？ 视乎没找到相关的配置。

#6

> 另外，进程结束时，如何Recv清空Channel的数据到文件。

#16

**Comment by Tomao2014** [comment]
已解决，感谢
