### ISSUE TITLE
切换ftlog记录位置时出现BUG

### ISSUE THREAD

**Issue by Yshelgi** [nonconvextech/ftlog#8]
场景:
首先设置一个文件夹使用ftlog进行日志记录一切正常,当我这个时候切换文件夹需要再次用builder()在新的文件夹路径下创建日志文件时就会报错.

`sender closed without sending a Quit first, this is a bug, channel is empty and disconnected`

**Comment by fMeow** [comment]
可以给个最小复现代码例子吗

**Comment by Yshelgi** [comment]
> 可以给出一个最小的复现代码例子吗？

感谢回复我的issue,下面是我写的一个demo请您看看
```
use ftlog::{info, error};
use ftlog::appender::FileAppender;

fn log_init(init_path:String){
    let log_path = format!("{}/{}",&init_path,"demo.log");
    let dest = FileAppender::new(&log_path);
    ftlog::Builder::new().root(dest).build().unwrap().init().unwrap();
    info!("Log file init");
}

fn main() {
    let path1 = String::from("./dir1");
    let path2 = String::from("./dir2");
    log_init(path1);
    log_init(path2);
}
```
主要就是对不同路径进行日志初始化操作时会出现上面的错误,本质上log只用初始化一次但是我想针对不同文件夹分别在其路径下创建日志文件以记录操作信息,这就要求切换时必须关闭上一个log所使用的相关资源不过没有看到有关于关闭相关操作的api

**Comment by fMeow** [comment]
`log`库是以全局变量的方式来存储log实例的。确实是不能初始化两次。

如果是想将完全相同的日志内容输出到两个不同文件夹，这个目前是不支持的。
如果是代码中不同位置的日志输出到不同文件夹，这个是支持的，比如mod A和mod B的日志输出到两个不同的文件夹。

**Comment by fMeow** [comment]
0.2.10版本中增加了[`ChainAppenders`](https://docs.rs/ftlog/0.2.10/ftlog/appender/struct.ChainAppenders.html)类型，以支持将日志同时输出到不同的地方，下面的例子将日志同时输出到`dir1/mylog.log`文件和`dir2/mylog.log`中。
```rust
    let writer1 = FileAppender::builder()
        .path("./dir1/mylog.log")
        .build();
    let writer2 = FileAppender::builder()
        .path("./dir2/mylog.log")
        .build();
    ftlog::Builder::new()
        .root(ChainAppenders::new(vec![
            Box::new(writer1),
            Box::new(writer2),
        ]))
        .try_init()
        .expect("logger build or set failed");
```
